language: rust
arch:
  - amd64
  - ppc64le
rust:
  - stable
  - nightly

branches:
  except:
    - staging.tmp

before_install:
  # Do not run bors builds against the nightly compiler.
  # We want to find out about nightly bugs, so they're done in master, but we don't block on them.
  - if [[ $TRAVIS_RUST_VERSION == "nightly" && $TRAVIS_BRANCH == "staging" ]]; then exit; fi

script:
  - cargo check
  - cargo test --release
  # check out memcpy-find and scan the output on a few samples
